name: blaseballstatus
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  args: ^2.1.1  
  cron: ^0.3.0
  http: ^0.13.3
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.0.5
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
  pedantic: ^1.9.0
  test: ^1.15.3
