name: blaseballstatus
description: An attempt to replicate PlayoffStatus.com for Blaseball.
author: Brian G. <mixolyde@gmail.com>
version: 0.0.7
homepage: https://mixolyde.net/blaseballstatus/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.1  
  cron: ^0.3.0
  http: ^0.13.3
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.0.6
  build_test: ^2.1.1
  build_web_compilers: ^3.0.0
  meta: 1.6.0
  pedantic: ^1.11.1
  test: ^1.17.9
