name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - name: Install dependencies
      run: dart pub get
    - name: Run tests with coverage
      env:
        AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}
      run: dart run test --coverage="coverage"
    - name: Convert coverage to ICOV
      run: dart pub run coverage:format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.packages --check-ignore --report-on=lib
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: coverage.lcov
